project:
  type: website
  output-dir: docs
website:
  title: "REACTPLOTS"
  site-url: "https://bougioukas.github.io/reactplots/"
  favicon: "img/logo.png"
  reader-mode: true
  navbar:
    right:
      - text: Basic plots
        menu:
          - text: Area plot
            href: projects.qmd 
          - text: Bar plot
            href: projects.qmd                
          - text: Box plot
            href: projects.qmd
          - text: Histogram
            href: projects.qmd  
          - text: Line plot
            href: projects.qmd                  
          - text: Scatterplot
            href: projects.qmd              
      - text: Specialized plots
        menu:
          - text: ROC curve
            href: projects.qmd
          - text: Kaplan–Meier curve
            #href: projects.qmd
            href: km_curve.qmd 
      - text: Networks
        menu:
          - text: Chord diagram
            href: projects.qmd
          - text: Graph (Network)
            href: projects.qmd
      - text: Flow diagrams
        menu:
          - text: Sankey diagram
            href: projects.qmd
          - text: Tree diagram
            href: shiny_interact.qmd                  
      - text: Maps
        menu:
          - text: Area (geographic) map
            href: projects.qmd
          - text: Choropleth map
            href: projects.qmd
          - text: Isopleth map
            href: projects.qmd                  
    pinned: true
    logo: "img/logo.png"
    tools:
      - icon: github
        href: https://github.com/bougioukas/reactplots
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)^®^"
    left: "&copy; Copyright 2024, Konstantinos I. Bougioukas. License: [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)."
  back-to-top-navigation: true
format:
  html:
    smooth-scroll: true
    theme: 
      - custom.scss
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 300px
      gutter-width: 1.5em
    fontsize: 1.10em
    linestretch: 1.35      
    link-external-newwindow: true
    toc: true
    toc-location: right
    citations-hover: true
    footnotes-hover: true
    #code-link: true
editor: source

